import Foundation

struct GlobalCacheRule: ClassificationRule {
    let category: StorageCategory = .cache
    func matches(url: URL) -> Bool {
        let path = url.path
        return path.contains("/Library/Caches")
    }
}

struct CacheSafetyRule: SafetyRule {
    func evaluate(url: URL, category: StorageCategory) -> (level: SafetyLevel, explanation: String)? {
        guard category == .cache else { return nil }
        return (.safe, "Cache files are generated by applications to speed up operations and can normally be safely regenerated.")
    }
}
